"""NLI entailment gate using DeBERTa-v3-xsmall zero-shot classifier.

Part of the 6-layer guardrail (A6 — Layer 5): every SUPPORTED section
generated by the LLM (T4:AI tier) is verified against the retrieved
evidence chunks. If the entailment probability is below the threshold
(0.75), ``post_verify`` emits a ``[CRITICAL]`` error that triggers the
verify→generate retry loop.

The underlying model
(``MoritzLaurer/deberta-v3-xsmall-zeroshot-v1.1-all-33``) is downloaded
via ``scripts/download_nli_model.py`` into ``models/nli/`` and is *not*
checked into git. The model is a binary NLI classifier with labels
``{0: 'entailment', 1: 'not_entailment'}``; we use it directly via
``AutoModelForSequenceClassification`` rather than through the
``zero-shot-classification`` pipeline because the direct
premise/hypothesis path gives cleaner separation on Korean medical
inputs (empirically: entailed pairs land near 0.97, unrelated pairs
near 0.5 — the zero-shot template wrapper compresses this range).
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

# Resolve the repository-root-relative model directory.
# nli_gate.py lives at: <repo>/src/pillcare/nli_gate.py
# parents[0]=pillcare, [1]=src, [2]=<repo-root>
MODEL_PATH = Path(__file__).resolve().parents[2] / "models" / "nli"

ENTAILMENT_THRESHOLD = 0.75


@lru_cache(maxsize=1)
def _load_model_and_tokenizer():
    """Load the DeBERTa NLI model + tokenizer lazily.

    Cached so importing this module does not pull in ``torch`` /
    ``transformers`` and, more importantly, does not trigger the
    multi-second model-load cost until the first real call.
    """
    from transformers import (  # type: ignore[import-not-found]
        AutoModelForSequenceClassification,
        AutoTokenizer,
    )

    tokenizer = AutoTokenizer.from_pretrained(str(MODEL_PATH))
    model = AutoModelForSequenceClassification.from_pretrained(str(MODEL_PATH))
    model.eval()  # disable dropout etc.
    return model, tokenizer


def check_entailment(claim: str, evidence: str) -> float:
    """Return entailment probability in [0.0, 1.0] that ``evidence`` supports ``claim``.

    Treats ``evidence`` as the NLI premise and ``claim`` as the
    hypothesis. Returns the softmax probability for the model's
    ``entailment`` class. Empty / whitespace-only inputs short-circuit
    to ``0.0`` without loading the model.
    """
    if not claim.strip() or not evidence.strip():
        return 0.0

    import torch  # type: ignore[import-not-found]

    model, tokenizer = _load_model_and_tokenizer()
    inputs = tokenizer(
        evidence,
        claim,
        return_tensors="pt",
        truncation=True,
        max_length=512,
    )
    with torch.no_grad():
        logits = model(**inputs).logits
    probs = torch.softmax(logits, dim=-1)[0]

    # Identify the entailment class index from the model config so we
    # aren't tied to positional order.
    id2label = {int(k): str(v).lower() for k, v in model.config.id2label.items()}
    entailment_idx = next(
        (i for i, lbl in id2label.items() if lbl.startswith("entail")),
        0,
    )
    return float(probs[entailment_idx].item())


def passes_nli_gate(
    claim: str, evidence: str, threshold: float = ENTAILMENT_THRESHOLD
) -> bool:
    """True iff entailment probability is at least ``threshold``."""
    return check_entailment(claim, evidence) >= threshold
